routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::get('/bonus', function () {
    return view('bonus_pertama');
});
Route::get('/home', 'UserController@index')->name('home');
Route::group(
    ['prefix' => 'super-admin', 'middleware'=>['auth', 'role:Super Admin']],
function () {
    Route::resource('/user', 'UserController');
}
);

app/Permission.php
<?php

namespace App;

use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    //
}

app/Role.php
<?php

namespace App;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    public function User() {
		return $this->belongsToMany('App\User', 'role_user','user_id', 'role_id');
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_name', 'nama_user','jabatan', 'password', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function Role() {
		return $this->belongsToMany('App\Role', 'role_user','user_id', 'role_id');
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Laratrust\LaratrustFacade as Laratrust;
use App\Surat_masuk;
use App\Surat_keluar;
use App\Disposisi;
use App\Instansi;
use App\User;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usr = User::count();
        $masuk = Surat_masuk::count();
        $keluar = Surat_keluar::count();
        $disposisi = Disposisi::count();
        $instansi = Instansi::count();

        return view('home',compact('usr', 'masuk', 'keluar', 'disposisi', 'instansi'));
        // if(Laratrust::hasRole('Super Admin')) return $this->adminDashboard();
        // if(Laratrust::hasRole('Admin')) return $this->memberDashboard();
    }
        // protected function adminDashboard()
        // {
        //     return view('home');
        // }
        // protected function adminDashboard()
        // {
        //     return view('welcome');
        // }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use File;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usr= User::with('role')->get();
        return view('User.indexuser', compact('usr'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('User.creater');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'user_name'=>'required|max:255|unique:users',
            'nama_user'=>'required|max:255',
            'password'=> 'required|min:6|confirmed',
        ]);
        $usr = new User;
        $usr->user_name = $request->user_name;
        $usr->nama_user = $request->nama_user;
        $usr->password = bcrypt('$request->password');
        $usr->save();
        $memberRole = Role::where('name', 'Admin')->first();
        $usr->attachRole($memberRole);
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('User.edit', compact('usr'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $usr = User::findOrfail($id);
        return view('User.edit', compact('usr'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'user_name'=>'required|max:255',
            'nama_user'=>'required|max:255',
            'password'=> 'required|min:6|confirmed',

        ]);
        $usr = User::findOrFail($id);
        $usr->user_name = $request->user_name;
        $usr->nama_user = $request->nama_user;
        $usr->password = bcrypt($request->password);
        $usr->save();
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $usr = User::FIndOrFail($id);
        $usr->delete();
        return redirect()->route('user.index');
    }
}

resources/views/User/create.blade.php
<div class="modal fade" id="tambah" tabindex="-1" role="dialog" aria-labelledby="tambahLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="tambahLabel">Tambah Data user <i class="fa fa-laptop"></i></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <form action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="cc-payment" class="control-label mb-1">Username</label>
                                <input id="cc-pament" name="user_name" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                <label for="cc-payment" class="control-label mb-1">Nama</label>
                                <input id="cc-pament" name="nama_user" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                <label for="cc-payment" class="control-label mb-1">Password</label>
                                <input id="cc-pament" name="password" type="password" class="form-control" aria-required="true" aria-invalid="false">
                                <label for="cc-payment" class="control-label mb-1">Confirm Password</label>
                                <input id="cc-pament" name="password_confirmation" type="password" class="form-control" aria-required="true" aria-invalid="false">
                            </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-info" data-dismiss="modal"><i class="fa fa-cloud"></i> Batal</button>
                <button type="submit" class="btn btn-outline-primary">
                    <i class="fa fa-check"></i>
                    Simpan
                </button>
                    </form>
            </div>
        </div>
    </div>
</div>

resources/views/User/creater.blade.php
@extends('layouts.app')
@section('content')
<div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row m-t-30">
                <div class="col-md-12">
                    <div class="m-b-10">
                            <div class="card card-dark" >
                            <div class="card-header">
                                    <h3 class="card-title">Add Data User
                                            <div class="panel-title pull-right">
												<i class="fa fa-mail-reply btn btn-outline-info"><a href="{{ url('/home')}}"> Kembali</a></i>
                                            </div>
                                        </h3>
                                    </div>
							<div class="card-body">
								<form action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
									{{ csrf_field() }}
									<div class="form-group {{ $errors->has('user_name') ? 'has-error' : '' }}">
										<label class="control-label">Username</label>
										<input type="text" name="user_name" class="form-control"  required>
										@if ($errors->has('user_name'))
											<span class="help-block">
												<strong>{{ $errors->first('user_name') }}</strong>
											</span>
										@endif
										</div>
										<div class="form-group {{ $errors->has('nama_user') ? 'has-error' : '' }}">
											<label class="control-label">Nama</label>
											<input type="text" name="nama_user" class="form-control"  required>
											@if ($errors->has('nama_user'))
												<span class="help-block">
													<strong>{{ $errors->first('nama_user') }}</strong>
												</span>
											@endif
										</div>
										<div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
											<label class="control-label">Password</label>
											<input type="password" name="password" class="form-control"  required>
											@if ($errors->has('password'))
												<span class="help-block">
													<strong>{{ $errors->first('password') }}</strong>
												</span>
											@endif
											</div>
											<div class="form-group ">
												<label for="password-confirm" class="control-label">{{ __('Confirm Password') }}</label>
													<input id="password-confirm" type="password" class="form-control" name="password_confirmation"  required>
											</div>
									<div>
                                    <button type="submit" class="btn btn-outline-primary">
                                            <i class="fa fa-check"></i>
                                            Add
                                        </button>
							</div>
						</form>
				</div>
			</div>
		</div>
    </div>
</div>
</div>
@endsection

resources/views/User/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row m-t-30">
                <div class="col-md-12">
                    <div class="m-b-10">
                            <div class="card card-dark" >
                            <div class="card-header">
                                    <h3 class="card-title">Edit Data User
                                            <div class="panel-title pull-right">
												<i class="fa fa-mail-reply btn btn-outline-info"><a href="{{ url('/home')}}"> Kembali</a></i>
                                            </div>
                                        </h3>
                                    </div>
							<div class="card-body">
								<form action="{{ route('user.update',$usr->id) }}" method="post" enctype="multipart/form-data">
									<input type="hidden" name="_method" value="PATCH">
									{{ csrf_field() }}
									<div class="form-group {{ $errors->has('user_name') ? 'has-error' : '' }}">
										<label class="control-label">Username</label>
										<input type="text" name="user_name" class="form-control" value="{{$usr->user_name }}" required>
										@if ($errors->has('user_name'))
											<span class="help-block">
												<strong>{{ $errors->first('user_name') }}</strong>
											</span>
										@endif
										</div>
										<div class="form-group {{ $errors->has('nama_user') ? 'has-error' : '' }}">
											<label class="control-label">Nama</label>
											<input type="text" name="nama_user" class="form-control" value="{{$usr->nama_user}}" required>
											@if ($errors->has('nama_user'))
												<span class="help-block">
													<strong>{{ $errors->first('nama_user') }}</strong>
												</span>
											@endif
										</div>
										<div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
											<label class="control-label">Password</label>
											<input type="password" name="password" class="form-control"  required>
											@if ($errors->has('password'))
												<span class="help-block">
													<strong>{{ $errors->first('password') }}</strong>
												</span>
											@endif
											</div>
											<div class="form-group ">
												<label for="password-confirm" class="control-label">{{ __('Confirm Password') }}</label>
													<input id="password-confirm" type="password" class="form-control" name="password_confirmation"  required>
											</div>
									<div>
                                    <button type="submit" class="btn btn-outline-primary">
                                            <i class="fa fa-check"></i>
                                            Ubah
                                        </button>
							</div>
						</form>
				</div>
			</div>
		</div>
    </div>
</div>
</div>
@endsection

resources/views/User/indexuser.blade.php
@extends('layouts.app')
@section('css')
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
@endsection
@section('content')
<!-- Font Awesome -->
<div class="section__content section__content--p30">
<div class="container-fluid">
    <div class="row m-t-30">
        <div class="col-md-12">
            <div class="m-b-10">
                    <div class="card card-dark" >
            <div class="card-header">
                <h3 class="card-title">Data User
                    <a href= "{{ route('user.create') }}"class="btn btn-outline-success float-right fa fa-pencil-square-o">
                    <i class="fa fa-pencil-square-o; "></i>
                    Tambah Data
                    </a>
            </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-borderless table-data3"style="font-size:11pt">
                <thead>
                <tr>
                    <th>No #</th>
                    <th>Username</th>
                    <th>Nama</th>
                    <th colspan="2">Action</th>
                </tr>
                </thead>
                <tbody>
                        @php
                          $no = 1;
                        @endphp
                        @foreach ($usr as $data)
                        <tr>
                          <td>{{ $no++ }}</td>
                          <td>{{ $data->user_name }}</td>
                          <td>{{ $data->nama_user }}</td>
                          <td>
                            <a href="{{ route('user.edit', $data->id) }}" class="btn btn-outline-primary">Edit</a>
                          </td>
                          <td>
                            <form action="{{ route('user.destroy', $data->id) }}" method="post">
                              <input type="hidden" name="_token" value="{{ csrf_token() }}">
                              <input type="hidden" name="_method" value="DELETE">
                              <button type="submit" class="btn btn-outline-danger">Delete</button>
                            </form>
                          </td>
                        </tr>
                        @endforeach
                      </tbody>
            </table>
        </div>
    </div>
</div>
</div>
      </div>
  </div>
</div>
@include('User.create')
@endsection

resources/views/bonus_pertama.blade.php
@extends('layouts.app')
@section('content')
<?php

$i;
for ($i = 1; $i <= 24; $i++)
{
    if ($i % 2 == 0 && $i % 3 == 0)
        echo "CodilityTest" . '<br>';

    else if ($i % 2 == 0 && $i % 5 == 0)
        echo "CodilityCoders" . '<br>';

    else if ($i % 3 == 0 && $i % 5 == 0)
        echo "TestCoders" . '<br>';

    else if (($i % 2) == 0)
        echo "Codility" . '<br>';

    else if (($i % 3) == 0)
        echo "Test" . '<br>';

    else if (($i % 5) == 0)
        echo "Coders" . '<br>';

    else
        echo $i,"  " ;
}

?>
@endsection

resources/views/home.blade.php
@extends('layouts.admin')
@section('css')
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
@endsection
@section('js')
<script src="{{ asset('assets/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('assets/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
@endsection

@section('content')
<!-- Main content -->
<section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        @role('Super Admin')
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info-gradient">
              <div class="inner">
                <h3>{{$usr}}</h3>

                <p>User</p>
              </div>
              <div class="icon">
              <i class="fa fa-user-plus" style="font-size:75px"></i>
              </div>
            <a href="{{route('user.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-dark-gradient">
              <div class="inner">
                <h3>{{$masuk}}</h3>

                <p>Surat Masuk</p>
              </div>
              <div class="icon">
                <i class="fa fa-envelope" style="font-size:75px"></i>
              </div>
            <a href="{{route('suratmasuk.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{$keluar}}</h3>

                <p>Surat Keluar</p>
              </div>
              <div class="icon">
                <i class="fa fa-paper-plane"style="font-size:75px"></i>
              </div>
              <a href="{{route('suratkeluar.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-primary-gradient" style="color:whitesmoke">
              <div class="inner">
                <h3>{{$disposisi}}</h3>

                <p>Disposisi</p>
              </div>
              <div class="icon">
                <i class="fa fa-exchange" style="font-size:75px"></i>
              </div>
              <a href="{{route('disposisi.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
        </div>
        @else
        <div class="row">
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-info-gradient">
                <div class="inner">
                  <h3>{{$instansi}}</h3>

                  <p>Instansi</p>
                </div>
                <div class="icon">
                <i class="fa fa-briefcase" style="font-size:75px"></i>
                </div>
              <a href="{{route('instansi.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-dark-gradient">
                <div class="inner">
                  <h3>{{$masuk}}</h3>

                  <p>Surat Masuk</p>
                </div>
                <div class="icon">
                  <i class="fa fa-envelope" style="font-size:75px"></i>
                </div>
              <a href="{{route('suratmasuk.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-success">
                <div class="inner">
                  <h3>{{$keluar}}</h3>

                  <p>Surat Keluar</p>
                </div>
                <div class="icon">
                  <i class="fa fa-paper-plane"style="font-size:75px"></i>
                </div>
                <a href="{{route('suratkeluar.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
              <!-- small box -->
              <div class="small-box bg-primary-gradient" style="color:whitesmoke">
                <div class="inner">
                  <h3>{{$disposisi}}</h3>

                  <p>Disposisi</p>
                </div>
                <div class="icon">
                  <i class="fa fa-exchange" style="font-size:75px"></i>
                </div>
                <a href="{{route('disposisi.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
          </div>
          @endrole
        <!-- /.row -->
        <!-- Main row -->
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </section>
          <!-- right col -->
        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <a class="navbar-brand" href="{{ url('/home') }}">
                    Crud User
                </a>
                <a class="navbar-brand" href="bonus">
                    Bonus Pertama
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>